#!/usr/bin/env bash
# =============================================================
# build-skill-tree.sh — Generate and validate the Bugsee skill tree
# =============================================================
# Scans every skills/*/SKILL.md, regenerates SKILL_TREE.md, and
# validates frontmatter, breadcrumbs, and router-table registration.
#
# Usage:
#   scripts/build-skill-tree.sh           # regenerate + validate
#   scripts/build-skill-tree.sh --check   # validate only (no write)
#
# Exit codes: 0 = pass, 1 = errors found
# Requirements: bash 3.2+, awk, sed, grep, find, diff
# =============================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"
TREE_FILE="$REPO_ROOT/SKILL_TREE.md"

CHECK_ONLY=false
case "${1:-}" in
  "")      ;;
  --check) CHECK_ONLY=true ;;
  *)       echo "unknown argument: $1 (usage: build-skill-tree.sh [--check])" >&2; exit 2 ;;
esac

ERRORS=0
err() { echo "ERROR: $*" >&2; ERRORS=$((ERRORS + 1)); }

# Read a single frontmatter field from a SKILL.md file.
fm() {
  awk -v k="$2" '
    NR==1 && $0=="---" { f=1; next }
    f && $0=="---" { exit }
    f {
      i=index($0,":")
      if (i) {
        key=substr($0,1,i-1); gsub(/^[ \t]+|[ \t]+$/,"",key)
        if (key==k) {
          v=substr($0,i+1); gsub(/^[ \t]+|[ \t]+$/,"",v); gsub(/^"|"$/,"",v)
          print v; exit
        }
      }
    }' "$1"
}

# First sentence of a string: cut at the first ". " that is followed by an
# uppercase letter. (An abbreviation followed by a Capitalized word would still
# truncate early; the current descriptions don't hit that case.)
first_sentence() { printf '%s' "$1" | sed -E 's/\. ([A-Z]).*/./'; }

# First non-frontmatter, non-blank body line of a SKILL.md.
first_body_line() {
  awk '/^---$/ { c++; next } c>=2 && NF { print; exit }' "$1"
}

# ---- Gather skills -------------------------------------------------
SKILLS=()
for d in "$SKILLS_DIR"/*/; do
  [ -f "${d}SKILL.md" ] || continue
  SKILLS+=("$(basename "$d")")
done
[ ${#SKILLS[@]} -gt 0 ] || { err "no skills found in $SKILLS_DIR"; exit 1; }
IFS=$'\n' SKILLS=($(printf '%s\n' "${SKILLS[@]}" | sort)); unset IFS

# ---- Validate ------------------------------------------------------
for name in "${SKILLS[@]}"; do
  file="$SKILLS_DIR/$name/SKILL.md"
  fname="$(fm "$file" name)"
  desc="$(fm "$file" description)"
  cat="$(fm "$file" category)"
  parent="$(fm "$file" parent)"
  role="$(fm "$file" role)"

  [ "$fname" = "$name" ] || err "$name: frontmatter name '$fname' != directory name"
  [ -n "$desc" ] || err "$name: missing description"

  bl="$(first_body_line "$file")"
  case "$bl" in
    "> [All Skills]"*) : ;;
    *) err "$name: first body line must be an '> [All Skills](...)' breadcrumb" ;;
  esac

  if [ "$role" != "router" ]; then
    case "$cat" in
      sdk-setup|workflow|internal) ;;
      *) err "$name: unknown or missing category '$cat' (expected sdk-setup|workflow|internal)" ;;
    esac
  fi

  if [ "$role" = "router" ]; then
    [ -z "$parent" ] || err "$name: router must not have a parent"
  elif [ -n "$parent" ]; then
    pfile="$SKILLS_DIR/$parent/SKILL.md"
    if [ ! -f "$pfile" ]; then
      err "$name: parent router '$parent' not found"
    elif [ "$(fm "$pfile" role)" != "router" ]; then
      err "$name: parent '$parent' is not a router (missing 'role: router')"
    elif ! grep -qE "\]\(\.\./$name/SKILL\.md\)" "$pfile"; then
      err "$name: no router link to '$name' in parent '$parent' (expected a [...]( ../$name/SKILL.md ) link)"
    fi
  fi
done

# ---- Generate SKILL_TREE.md ----------------------------------------
emit_rows() { # category
  local want="$1" any=0 name cat desc
  for name in "${SKILLS[@]}"; do
    cat="$(fm "$SKILLS_DIR/$name/SKILL.md" category)"
    [ "$cat" = "$want" ] || continue
    desc="$(first_sentence "$(fm "$SKILLS_DIR/$name/SKILL.md" description)")"
    printf '| [`%s`](skills/%s/SKILL.md) | %s |\n' "$name" "$name" "$desc"
    any=1
  done
  [ "$any" = 1 ] || printf '| _none yet_ | |\n'
}

emit_routers() {
  local name role desc
  for name in "${SKILLS[@]}"; do
    role="$(fm "$SKILLS_DIR/$name/SKILL.md" role)"
    [ "$role" = "router" ] || continue
    desc="$(first_sentence "$(fm "$SKILLS_DIR/$name/SKILL.md" description)")"
    printf '| [`%s`](skills/%s/SKILL.md) | %s |\n' "$name" "$name" "$desc"
  done
}

generate() {
  cat <<'HEADER'
# Bugsee Skills

Structured skills that teach AI coding assistants to set up Bugsee SDKs, debug
crashes and bug reports via the Bugsee MCP server, and keep stack traces readable.

> This file is generated by `scripts/build-skill-tree.sh`. Do not edit it by hand —
> change a skill's frontmatter and re-run the script.

## How to Use These Skills

When installed as a Claude Code or Cursor plugin, the SDK and workflow skills are
bundled locally and loaded on demand by the router skills below. Standalone, fetch
the canonical SDK skills from `https://docs.bugsee.com/ai/agent-skills/`.

## Entry Points

| Router | What it does |
|---|---|
HEADER
  emit_routers
  cat <<'SDK'

## SDK Setup

Install and configure Bugsee for a platform. The `bugsee-sdk-setup` router detects
the platform and loads the right skill.

| Skill | What it does |
|---|---|
SDK
  emit_rows "sdk-setup"
  cat <<'WF'

## Workflows

Debug Bugsee issues and keep crash reports readable.

| Skill | What it does |
|---|---|
WF
  emit_rows "workflow"
  cat <<'INT'

## Internal

Contributor tooling for authoring and maintaining skills.

| Skill | What it does |
|---|---|
INT
  emit_rows "internal"
}

GENERATED="$(generate)"

if [ -f "$TREE_FILE" ] && [ "$GENERATED" = "$(cat "$TREE_FILE")" ]; then
  echo "SKILL_TREE.md is up to date."
else
  if $CHECK_ONLY; then
    echo "SKILL_TREE.md diff (existing -> generated):"
    diff <(cat "$TREE_FILE" 2>/dev/null) <(printf '%s\n' "$GENERATED") || true
    err "SKILL_TREE.md is stale. Run scripts/build-skill-tree.sh to regenerate."
  else
    printf '%s\n' "$GENERATED" > "$TREE_FILE"
    echo "SKILL_TREE.md written."
  fi
fi

# ---- Summary -------------------------------------------------------
if [ "$ERRORS" -gt 0 ]; then
  echo "FAILED with $ERRORS error(s)." >&2
  exit 1
fi
echo "OK — ${#SKILLS[@]} skills validated."
